"""add chatbot

Revision ID: 14f48106f20d
Revises: fc11ed8b2b7c
Create Date: 2025-04-24 09:57:51.924018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f48106f20d'
down_revision = 'fc11ed8b2b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_user_id'), ['user_id'], unique=False)

    op.create_table('chatbot_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_knowledge_knowledge_id'), ['knowledge_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_knowledge_knowledge_id'))

    op.drop_table('chatbot_knowledge')
    with op.batch_alter_table('chatbot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatbot_title'))

    op.drop_table('chatbot')
    # ### end Alembic commands ###
