"""update knowledge table

Revision ID: fc11ed8b2b7c
Revises: f020f3ca09e0
Create Date: 2025-04-24 08:56:06.474678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc11ed8b2b7c'
down_revision = 'f020f3ca09e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_knowledge_base_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_base_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
